Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/adding-and-dropping-columns](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/adding-and-dropping-columns)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## Adding and Dropping Columns

### Adding

Assign the same value to every row:

In [2]:
df = pd.DataFrame({"A": [1, 2, 3]})
df["B"] = 10
df

   A   B
0  1  10
1  2  10
2  3  10

Assigning a list or array:

In [3]:
df["C"] = [100, 200, 300]
df

   A   B    C
0  1  10  100
1  2  10  200
2  3  10  300

Using calculations on existing columns:

In [4]:
df["D"] = df["A"] + df["C"]
df

   A   B    C    D
0  1  10  100  101
1  2  10  200  202
2  3  10  300  303

Using .assign():

In [5]:
df = df.assign(E=df["D"] * 2)
df

   A   B    C    D    E
0  1  10  100  101  202
1  2  10  200  202  404
2  3  10  300  303  606

Using .insert():

In [6]:
df.insert(1, "F", [7, 8, 9])
df

   A  F   B    C    D    E
0  1  7  10  100  101  202
1  2  8  10  200  202  404
2  3  9  10  300  303  606

---

### Dropping

Using .drop():

In [7]:
df.drop("B", axis=1, inplace=True) 
df

   A  F    C    D    E
0  1  7  100  101  202
1  2  8  200  202  404
2  3  9  300  303  606

Drop multiple columns:

In [8]:
df.drop(["C", "D"], axis=1, inplace=True)
df

   A  F    E
0  1  7  202
1  2  8  404
2  3  9  606

Using del:

In [9]:
del df["F"]
df

   A    E
0  1  202
1  2  404
2  3  606

Using .pop()

In [10]:
popped_column = df.pop("E")
popped_column

0    202
1    404
2    606
Name: E, dtype: int64

In [11]:
df

   A
0  1
1  2
2  3