Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/concatenate-merge-join](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/concatenate-merge-join)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## Concatenate, Merge & Join

Concatenate:

In [2]:
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df2 = pd.DataFrame({"A": [5, 6], "B": [7, 8]})

pd.concat([df1, df2], ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

Merge (pd.merge):

In [3]:
df1 = pd.DataFrame({"ID": [1, 2, 3], "Name": ["Alice", "Bob", "Charlie"]})
df2 = pd.DataFrame({"ID": [2, 3, 4], "Salary": [50000, 60000, 70000]})

pd.merge(df1, df2, on="ID", how="inner")

   ID     Name  Salary
0   2      Bob   50000
1   3  Charlie   60000

Join (df.join):

In [4]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "ID": [1, 2]}).set_index("ID")
df2 = pd.DataFrame({"Salary": [50000, 60000]}, index=[1, 2])

df1.join(df2)

     Name  Salary
ID
1   Alice   50000
2     Bob   60000