Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/data-manipulation](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/data-manipulation)

--- 

Import Pandas and NumPy for the notebook:

In [1]:
import numpy as np
import pandas as pd

---
## Data Manipulation

### Renaming Columns

Create sample data:

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Bob"],
    "Age": [25, 30, 35, 40, 45],
    "Salary": [50000.32, 60000.56, 70000.23, 80000.12, 90000.00],
}

df = pd.DataFrame(data)
df

      Name  Age    Salary
0    Alice   25  50000.32
1      Bob   30  60000.56
2  Charlie   35  70000.23
3    David   40  80000.12
4      Bob   45  90000.00

Rename all columns at once:

In [3]:
df.columns = ["Name-new", "Age-new", "Salary-new"]
df

  Name-new  Age-new  Salary-new
0    Alice       25    50000.32
1      Bob       30    60000.56
2  Charlie       35    70000.23
3    David       40    80000.12
4      Bob       45    90000.00

Rename an individual column:

In [4]:
df.rename(columns={"Age-new": "Age Changed Again"}, inplace=True)
df

  Name-new  Age Changed Again  Salary-new
0    Alice                 25    50000.32
1      Bob                 30    60000.56
2  Charlie                 35    70000.23
3    David                 40    80000.12
4      Bob                 45    90000.00

Selecting Columns by Data Type:

In [5]:
# Select only numeric columns
df_numeric = df.select_dtypes(include=["number"])
df_numeric

   Age Changed Again  Salary-new
0                 25    50000.32
1                 30    60000.56
2                 35    70000.23
3                 40    80000.12
4                 45    90000.00

In [6]:
# Select only object (string) columns
df_object = df.select_dtypes(include=["object"])
df_object

  Name-new
0    Alice
1      Bob
2  Charlie
3    David
4      Bob

In [7]:
# Exclude float columns
df_no_float = df.select_dtypes(exclude=["float"])
df_no_float

  Name-new  Age Changed Again
0    Alice                 25
1      Bob                 30
2  Charlie                 35
3    David                 40
4      Bob                 45

Converting to NumPy

In [8]:
# returns a 2D NumPy array
df_array = df.values
df_array

array([['Alice', 25, 50000.32],
       ['Bob', 30, 60000.56],
       ['Charlie', 35, 70000.23],
       ['David', 40, 80000.12],
       ['Bob', 45, 90000.0]], dtype=object)

Replacing Data

In [9]:
# Replace a single value
df.replace("Bob", "Bob New", inplace=True)
df

  Name-new  Age Changed Again  Salary-new
0    Alice                 25    50000.32
1  Bob New                 30    60000.56
2  Charlie                 35    70000.23
3    David                 40    80000.12
4  Bob New                 45    90000.00

In [10]:
# Replace multiple values
df.replace([25,40,90000.00], [10,88,1000], inplace=True)
df

  Name-new  Age Changed Again  Salary-new
0    Alice                 10    50000.32
1  Bob New                 30    60000.56
2  Charlie                 35    70000.23
3    David                 88    80000.12
4  Bob New                 45     1000.00

In [11]:
# Replace in a single column
df["Name-new"] = df["Name-new"].replace("David", "Sally")
df

  Name-new  Age Changed Again  Salary-new
0    Alice                 10    50000.32
1  Bob New                 30    60000.56
2  Charlie                 35    70000.23
3    Sally                 88    80000.12
4  Bob New                 45     1000.00

Changing Data Types:

In [12]:
df.dtypes

Name-new              object
Age Changed Again      int64
Salary-new           float64
dtype: object

In [13]:
# Convert age column to float
df["Age Changed Again"] = df["Age Changed Again"].astype(float)
df.dtypes

Name-new              object
Age Changed Again    float64
Salary-new           float64
dtype: object