Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/dealing-with-missing-data-duplicates](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/dealing-with-missing-data-duplicates)

--- 

Import Pandas and NumPy for the notebook:

In [1]:
import pandas as pd
import numpy as np

Create sample data for the notebook:

In [2]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [25, np.nan, 35, 40],
    "City": ["New York", "Los Angeles", None, "Chicago"]
})
df

      Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie  35.0         None
3     None  40.0      Chicago

---
## Dealing with Missing Data & Duplicates

**.isnull()**:

In [3]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False

**.isnull().sum()**:

In [4]:
df.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

**.dropna()**:

In [5]:
df.dropna()

    Name   Age      City
0  Alice  25.0  New York

Reset data again:

In [6]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [25, np.nan, 35, 40],
    "City": ["New York", "Los Angeles", None, "Chicago"]
})
df

      Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie  35.0         None
3     None  40.0      Chicago

**.fillna()**:

In [7]:
df.fillna("Unknown")

      Name      Age         City
0    Alice     25.0     New York
1      Bob  Unknown  Los Angeles
2  Charlie     35.0      Unknown
3  Unknown     40.0      Chicago

Reset data again:

In [8]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [25, np.nan, 35, 40],
    "City": ["New York", "Los Angeles", None, "Chicago"]
})
df

      Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie  35.0         None
3     None  40.0      Chicago

Set the missing age as the mean of all ages:

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

      Name        Age         City
0    Alice  25.000000     New York
1      Bob  33.333333  Los Angeles
2  Charlie  35.000000         None
3     None  40.000000      Chicago

Change alice to alicia and none to unkown on the name column:

In [10]:
df["Name"] = df["Name"].replace({ None: "Unknown", "Alice": "Alicia"})
df

      Name        Age         City
0   Alicia  25.000000     New York
1      Bob  33.333333  Los Angeles
2  Charlie  35.000000         None
3  Unknown  40.000000      Chicago