Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/filtering](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/filtering)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

Sample data:

In [2]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "Salary": [50000, 60000, 75000, 80000]
})
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   80000

---
## Filtering

Single Condition

Using the boolean indexing, so what its actually passing in from the condition is the array of True/False values and only displaying the ones where the value equates to True.

In [3]:
filtered_df = df[df["Age"] > 30]
filtered_df

      Name  Age  Salary
2  Charlie   35   75000
3    David   40   80000

Multiple Conditions (AND / OR)

In [4]:
# Age > 30 AND Salary > 70000
df[(df["Age"] > 30) & (df["Salary"] > 70000)]

      Name  Age  Salary
2  Charlie   35   75000
3    David   40   80000

In [5]:
# Age < 35 OR Salary < 60000
df[(df["Age"] < 35) | (df["Salary"] < 60000)]

    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000

Using .query()

In [6]:
df.query("Age > 30 & Salary > 70000")

      Name  Age  Salary
2  Charlie   35   75000
3    David   40   80000

Filtering with .isin()

In [7]:
df[df["Name"].isin(["Alice", "David"])]

    Name  Age  Salary
0  Alice   25   50000
3  David   40   80000

Filtering with string methods

In [8]:
# Names starting with 'C'
df[df["Name"].str.startswith("C")]

      Name  Age  Salary
2  Charlie   35   75000

In [9]:
# Names containing 'a' (case-sensitive)
df[df["Name"].str.contains("a")]

      Name  Age  Salary
2  Charlie   35   75000
3    David   40   80000

Resetting Index after Filtering

In [10]:
filtered_df = df[df["Age"] > 30].reset_index(drop=True)
filtered_df

      Name  Age  Salary
0  Charlie   35   75000
1    David   40   80000