Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/groupby](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/groupby)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## GroupBy

Example:

In [2]:
data = {
    "Department": ["Sales", "Sales", "IT", "IT", "HR"],
    "Salary": [50000, 60000, 70000, 80000, 45000]
}
df = pd.DataFrame(data)

df.groupby("Department")["Salary"].mean()

Department
HR       45000.0
IT       75000.0
Sales    55000.0
Name: Salary, dtype: float64

Use .agg() for flexibility:

In [3]:
df.groupby("Department")["Salary"].agg(["mean", "sum", "max"])

               mean     sum    max
Department
HR          45000.0   45000  45000
IT          75000.0  150000  80000
Sales       55000.0  110000  60000

Grouping by Multiple Columns

In [4]:
df.groupby(["Department", "Salary"]).size()

Department  Salary
HR          45000     1
IT          70000     1
            80000     1
Sales       50000     1
            60000     1
dtype: int64

Example: normalise salaries within departments:

In [5]:
df["Salary_normalized"] = df.groupby("Department")["Salary"].transform(lambda x: x / x.mean())
df

  Department  Salary  Salary_normalized
0      Sales   50000           0.909091
1      Sales   60000           1.090909
2         IT   70000           0.933333
3         IT   80000           1.066667
4         HR   45000           1.000000

Use .filter() to drop groups based on a condition:

In [6]:
df.groupby("Department").filter(lambda x: x["Salary"].mean() > 60000)

  Department  Salary  Salary_normalized
2         IT   70000           0.933333
3         IT   80000           1.066667

Iterating Over Groups:

In [7]:
for name, group in df.groupby("Department"):
    print(name)
    print(group)

HR
  Department  Salary  Salary_normalized
4         HR   45000                1.0
IT
  Department  Salary  Salary_normalized
2         IT   70000           0.933333
3         IT   80000           1.066667
Sales
  Department  Salary  Salary_normalized
0      Sales   50000           0.909091
1      Sales   60000           1.090909