Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/importing-and-exporting-data](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/importing-and-exporting-data)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## **Importing and Exporting Data**


### **Importing CSV Files**


Local CSV read:

In [2]:
df = pd.read_csv('../datafiles/data.csv')
df

   ID     Name  Age         City
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston

Remote CSV file:

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/simplesteps-guide/pandas-basics/refs/heads/main/datafiles/data.csv')
df

   ID     Name  Age         City
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston

CSV without headers:

In [4]:
df = pd.read_csv('../datafiles/data_no_header.csv', header=None, names=['Name', 'Age', 'City'])
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

Read only selected columns:

In [5]:
df = pd.read_csv('../datafiles/data-extra.csv', usecols=['Name','Age'])
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

Use a column as index:

In [6]:
df = pd.read_csv('../datafiles/data-extra.csv', index_col='ID')
df

       Name  Age         City Country  Salary
ID
1     Alice   25     New York     USA   50000
2       Bob   30  Los Angeles     USA   60000
3   Charlie   35      Chicago     USA   55000
4     David   40      Houston     USA   65000

Parse dates:

In [7]:
df = pd.read_csv('../datafiles/sales.csv', parse_dates=['OrderDate'])
df

   OrderID  OrderDate Customer  Amount
0     1001 2025-09-01    Alice     250
1     1002 2025-09-02      Bob     300
2     1003 2025-09-03  Charlie     150
3     1004 2025-09-04    David     400

Handle missing values:

In [8]:
df = pd.read_csv('../datafiles/data2.csv', na_values=['', 'NA'])
df

   ID   Name   Age         City
0   1  Alice  25.0     New York
1   2    Bob   NaN  Los Angeles
2   3    NaN  35.0      Chicago
3   4  David  40.0          NaN

---
### **Exporting CSV Files**

Exclude index:

In [9]:
df.to_csv("../output_files/output_no_index.csv", index=False)

Change delimiter:

In [10]:
df.to_csv("../output_files/output_semicolon.csv", sep=';')

Select only certain columns:

In [11]:
df.to_csv("../output_files/output_subset.csv", columns=['Name', 'Age'], index=False)

Export to string instead of file:

In [12]:
csv_string = df.to_csv(index=False)
csv_string

'ID,Name,Age,City\n1,Alice,25.0,New York\n2,Bob,,Los Angeles\n3,,35.0,Chicago\n4,David,40.0,\n'

---
---

### **Importing JSON Files**

Records (list of dicts):

In [13]:
df = pd.read_json("../datafiles/data.json", orient="records")
df

   id   name  age
0   1  Alice   25
1   2    Bob   30

Index-based:

In [14]:
df = pd.read_json("../datafiles/data2.json", orient="index")
df

    name  age
1  Alice   25
2    Bob   30

Columns-based:

In [15]:
df = pd.read_json("../datafiles/data3.json", orient="columns")
df

    name  age
0  Alice   25
1    Bob   30

Line-delimited JSON (NDJSON):

In [16]:
df = pd.read_json("../datafiles/data4.json", lines=True)
df

   id   name  age
0   1  Alice   25
1   2    Bob   30

---
### Exporting JSON

Export to JSON string:

In [17]:
json_str = df.to_json(orient="records", indent=2)
json_str

'[\n  {\n    "id":1,\n    "name":"Alice",\n    "age":25\n  },\n  {\n    "id":2,\n    "name":"Bob",\n    "age":30\n  }\n]'

Export to JSON file:

In [18]:
df.to_json("../output_files/output.json", orient="records", indent=2)

---
---
### Importing HTML Tables

Read tables from a URL:

In [19]:
dfs = pd.read_html('https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/appendix-sample-html-tables-for-import-section')
dfs

[       0     1     2        3         4
 0   Name  Dogs  Cats  Budgies  Hamsters
 1    Bob     1     2        0         0
 2   Dave     0     1        0         0
 3   Jane     0     0        2         0
 4  Sally     3     0        0         1,
            0         1        2
 0     Animal  Num Legs     Type
 1      Horse         4   Mammal
 2        Dog         4   Mammal
 3  Gold Fish         0     Fish
 4  Alligator         4  Reptile
 5     Lizard         4  Reptile
 6     Budgie         2     Bird,
           0       1    2      3     4       5
 0      Team  Played  Won  Drawn  Lost  Points
 1    Team 1       4    4      0     0      12
 2    Team 2       3    3      0     0       9
 3    Team 3       3    3      0     0       9
 4    Team 4       4    2      1     1       7
 5    Team 5       4    2      1     1       7
 6    Team 6       4    2      0     2       6
 7    Team 7       4    1      1     2       4
 8    Team 8       4    1      0     3       3
 9    Team 9       4    0      1     3       1
 10  Team 10       4    0      0     4       0]

Finds 3 tables, so returns a list of 3 DataFrames.

To access the first one:

In [20]:
dfs[0]

       0     1     2        3         4
0   Name  Dogs  Cats  Budgies  Hamsters
1    Bob     1     2        0         0
2   Dave     0     1        0         0
3   Jane     0     0        2         0
4  Sally     3     0        0         1

or the 2nd:

In [21]:
dfs[1]

           0         1        2
0     Animal  Num Legs     Type
1      Horse         4   Mammal
2        Dog         4   Mammal
3  Gold Fish         0     Fish
4  Alligator         4  Reptile
5     Lizard         4  Reptile
6     Budgie         2     Bird