Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/index-and-multiindex](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/index-and-multiindex)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## Indexes

Example data:

In [2]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
})
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

You can set a column as the index using .set_index():

In [3]:
df.set_index("Name", inplace=True)
df

         Age
Name
Alice     25
Bob       30
Charlie   35

Now the index is Name, which can be used for label-based access:

In [4]:
df.loc["Bob"]

Age    30
Name: Bob, dtype: int64

---
## Multiindex

Creating MultiIndex - from arrays

In [5]:
arrays = [
    ["East", "East", "West", "West"],
    ["Store1", "Store2", "Store1", "Store2"]
]

index = pd.MultiIndex.from_arrays(arrays, names=("Region", "Store"))

df = pd.DataFrame({
    "Sales": [100, 150, 200, 250]
}, index=index)
df

               Sales
Region Store
East   Store1    100
       Store2    150
West   Store1    200
       Store2    250

Creating MultiIndex - from tuples

In [6]:
tuples = [("East", "Store1"), ("East", "Store2"), ("West", "Store1"), ("West", "Store2")]
index = pd.MultiIndex.from_tuples(tuples, names=("Region", "Store"))

df = pd.DataFrame({"Sales": [100,150,200,250]}, index=index)
df

               Sales
Region Store
East   Store1    100
       Store2    150
West   Store1    200
       Store2    250

Accessing MultiIndex data single level:

In [7]:
df.loc["East"]

        Sales
Store
Store1    100
Store2    150

Specific row:

In [8]:
df.loc[("East","Store2")]

Sales    150
Name: (East, Store2), dtype: int64

Slicing levels:

In [9]:
df.loc[pd.IndexSlice["East":"West", "Store1":"Store2"], :]

               Sales
Region Store
East   Store1    100
       Store2    150
West   Store1    200
       Store2    250

Sorting MultiIndex

In [10]:
# sort by first level
df.sort_index(level=0)

               Sales
Region Store
East   Store1    100
       Store2    150
West   Store1    200
       Store2    250

In [11]:
# sort by second level, then first
df.sort_index(level=[1,0])

               Sales
Region Store
East   Store1    100
West   Store1    200
East   Store2    150
West   Store2    250