Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/pipe](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/pipe)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## Pipe

Basic Example:

In [2]:
df = pd.DataFrame({
    "Sales": [100, 200, 300],
    "Cost": [50, 80, 120]
})

def add_profit(df):
    df["Profit"] = df["Sales"] - df["Cost"]
    return df

def add_margin(df):
    df["Margin"] = df["Profit"] / df["Sales"]
    return df

df_new = (
    df
    .pipe(add_profit)
    .pipe(add_margin)
)
df_new

   Sales  Cost  Profit  Margin
0    100    50      50     0.5
1    200    80     120     0.6
2    300   120     180     0.6

Using Arguments with .pipe():

In [3]:
def add_column(df, colname, value):
    df[colname] = value
    return df

df.pipe(add_column, "Discount", 0.1)
df

   Sales  Cost  Profit  Margin  Discount
0    100    50      50     0.5       0.1
1    200    80     120     0.6       0.1
2    300   120     180     0.6       0.1

Combining with lambda

In [4]:
df.pipe(lambda d: d.assign(Revenue=d["Sales"] * 1.2))

   Sales  Cost  Profit  Margin  Discount  Revenue
0    100    50      50     0.5       0.1    120.0
1    200    80     120     0.6       0.1    240.0
2    300   120     180     0.6       0.1    360.0