Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/pivot-tables-melt-stack-and-unstack](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/pivot-tables-melt-stack-and-unstack)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

---
## Pivot Tables, Melt, Stack, and Unstack

Example pivot table:

In [2]:
data = {
    "Department": ["Sales", "Sales", "IT", "IT", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "Dave", "Eve"],
    "Salary": [50000, 60000, 70000, 80000, 45000],
}
df = pd.DataFrame(data)

pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)
pivot

             Salary
Department
HR          45000.0
IT          75000.0
Sales       55000.0

Melt:

In [3]:
df = pd.DataFrame({
    "Employee": ["Alice", "Bob"],
    "Sales_Q1": [200, 150],
    "Sales_Q2": [210, 160]
})

melted = pd.melt(
    df,
    id_vars=["Employee"],
    value_vars=["Sales_Q1", "Sales_Q2"],
    var_name="Quarter",
    value_name="Sales"
)
melted

  Employee   Quarter  Sales
0    Alice  Sales_Q1    200
1      Bob  Sales_Q1    150
2    Alice  Sales_Q2    210
3      Bob  Sales_Q2    160

Stack:

In [4]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Math": [90, 80],
    "Science": [85, 95]
})
df

    Name  Math  Science
0  Alice    90       85
1    Bob    80       95

In [5]:
stacked = df.set_index("Name").stack()
stacked

Name
Alice  Math       90
       Science    85
Bob    Math       80
       Science    95
dtype: int64

Unstack:

In [6]:
unstacked = stacked.unstack()
unstacked

       Math  Science
Name
Alice    90       85
Bob      80       95