Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/selecting](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/selecting)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

Create sample data for notebook:

In [2]:
df = pd.DataFrame({
    "Col1": ["Alice", "Bob", "Charlie", "David", "Claire"],
    "Col2": [25, 30, 35, 40, 28],
    "Col3": ["New York", "Los Angeles", "Washington", "Chicago", "Houston"],
    "Col4": [50000, 60000, 70000, 80000, 55000],
    "Col5": [5.5, 6.0, 7.0, 8.0, 5.8],
    "Col6": [True, False, True, False, True],
    "other": ["A", "B", "C", "D", "E"]
})
df

      Col1  Col2         Col3   Col4  Col5   Col6 other
0    Alice    25     New York  50000   5.5   True     A
1      Bob    30  Los Angeles  60000   6.0  False     B
2  Charlie    35   Washington  70000   7.0   True     C
3    David    40      Chicago  80000   8.0  False     D
4   Claire    28      Houston  55000   5.8   True     E

---
## Selecting

Single column:

In [3]:
df["Col1"]

0      Alice
1        Bob
2    Charlie
3      David
4     Claire
Name: Col1, dtype: object

Multiple columns:

In [4]:
df[["Col1", "Col4"]]

      Col1   Col4
0    Alice  50000
1      Bob  60000
2  Charlie  70000
3    David  80000
4   Claire  55000

By index using .iloc[]:

In [5]:
# first row as Series
df.iloc[0]

Col1        Alice
Col2           25
Col3     New York
Col4        50000
Col5          5.5
Col6         True
other           A
Name: 0, dtype: object

In [6]:
# first three rows as DataFrame
df.iloc[0:3]

      Col1  Col2         Col3   Col4  Col5   Col6 other
0    Alice    25     New York  50000   5.5   True     A
1      Bob    30  Los Angeles  60000   6.0  False     B
2  Charlie    35   Washington  70000   7.0   True     C

In [7]:
# first and third rows
df.iloc[[0,2]]

      Col1  Col2        Col3   Col4  Col5  Col6 other
0    Alice    25    New York  50000   5.5  True     A
2  Charlie    35  Washington  70000   7.0  True     C

By label using .loc[]:

In [8]:
# row with index label 0
df.loc[0]

Col1        Alice
Col2           25
Col3     New York
Col4        50000
Col5          5.5
Col6         True
other           A
Name: 0, dtype: object

In [9]:
# rows with index labels 0,1,2 (inclusive)
df.loc[0:2]

      Col1  Col2         Col3   Col4  Col5   Col6 other
0    Alice    25     New York  50000   5.5   True     A
1      Bob    30  Los Angeles  60000   6.0  False     B
2  Charlie    35   Washington  70000   7.0   True     C

In [10]:
# all rows, only selected columns
df.loc[:, ["Col1","Col4"]]

      Col1   Col4
0    Alice  50000
1      Bob  60000
2  Charlie  70000
3    David  80000
4   Claire  55000

In [11]:
# subset of rows and columns
df.loc[0:2, ["Col1","Col4"]]

      Col1   Col4
0    Alice  50000
1      Bob  60000
2  Charlie  70000

Conditional Selection (Boolean Indexing):

In [12]:
# rows where Col2 > 30
df[df["Col2"] > 30]

      Col1  Col2        Col3   Col4  Col5   Col6 other
2  Charlie    35  Washington  70000   7.0   True     C
3    David    40     Chicago  80000   8.0  False     D

In [13]:
# conditional + column selection
df.loc[df["Col2"] > 30, ["Col1","Col4"]]

      Col1   Col4
2  Charlie  70000
3    David  80000

Single cell .at[] (label-based, single element):

In [14]:
# value at row index 0, column "Col1"
df.at[0, "Col1"]

'Alice'

Single cell .iat[] (integer position, single element):

In [15]:
# value at row 0, column 2 (0-based position)
df.iat[0, 2]

'New York'

Slicing - Rows:

In [16]:
# first 3 rows (like iloc)
df[0:3]

      Col1  Col2         Col3   Col4  Col5   Col6 other
0    Alice    25     New York  50000   5.5   True     A
1      Bob    30  Los Angeles  60000   6.0  False     B
2  Charlie    35   Washington  70000   7.0   True     C

Slicing - Columns:

In [17]:
# columns Col1 to Col4 (inclusive)
df.loc[:, "Col1":"Col4"]

      Col1  Col2         Col3   Col4
0    Alice    25     New York  50000
1      Bob    30  Los Angeles  60000
2  Charlie    35   Washington  70000
3    David    40      Chicago  80000
4   Claire    28      Houston  55000

Selecting with .filter():

In [18]:
# select specific columns
df.filter(items=["Col1","Col4"])

      Col1   Col4
0    Alice  50000
1      Bob  60000
2  Charlie  70000
3    David  80000
4   Claire  55000

In [19]:
# select columns containing 'Col'
df.filter(like="Col")

      Col1  Col2         Col3   Col4  Col5   Col6
0    Alice    25     New York  50000   5.5   True
1      Bob    30  Los Angeles  60000   6.0  False
2  Charlie    35   Washington  70000   7.0   True
3    David    40      Chicago  80000   8.0  False
4   Claire    28      Houston  55000   5.8   True