Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/sorting](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/sorting)

--- 

Import Pandas for the notebook:

In [1]:
import pandas as pd

Sample data for the examples:

In [2]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "Salary": [50000, 60000, 75000, 80000]
})
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   80000

---
## Sorting

Sort by Single Column

In [3]:
# Sort by Age ascending (default)
df.sort_values("Age", inplace=True)
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   80000

Sort Descending

In [4]:
df.sort_values("Salary", ascending=False, inplace=True)
df

      Name  Age  Salary
3    David   40   80000
2  Charlie   35   75000
1      Bob   30   60000
0    Alice   25   50000

Sort by Multiple Columns

In [5]:
# Sort by Age ascending, then Salary descending
df.sort_values(["Age", "Salary"], ascending=[True, False], inplace=True)
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   80000