Examples for [https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/time-series-data](https://simplesteps.guide/guides/technology/machine-learning-ai/pandas-basics/time-series-data)

--- 

Import Pandas and NumPy for the notebook:

In [1]:
import numpy as np
import pandas as pd

---

## Time Series Data

Creating DatetimeIndex:

In [2]:
index = pd.date_range(start='27/10/2019 00:00:00', periods=24, freq='h')
index

DatetimeIndex(['2019-10-27 00:00:00', '2019-10-27 01:00:00',
               '2019-10-27 02:00:00', '2019-10-27 03:00:00',
               '2019-10-27 04:00:00', '2019-10-27 05:00:00',
               '2019-10-27 06:00:00', '2019-10-27 07:00:00',
               '2019-10-27 08:00:00', '2019-10-27 09:00:00',
               '2019-10-27 10:00:00', '2019-10-27 11:00:00',
               '2019-10-27 12:00:00', '2019-10-27 13:00:00',
               '2019-10-27 14:00:00', '2019-10-27 15:00:00',
               '2019-10-27 16:00:00', '2019-10-27 17:00:00',
               '2019-10-27 18:00:00', '2019-10-27 19:00:00',
               '2019-10-27 20:00:00', '2019-10-27 21:00:00',
               '2019-10-27 22:00:00', '2019-10-27 23:00:00'],
              dtype='datetime64[ns]', freq='h')

Creating DataFrame example:

In [3]:
np.random.seed(3)
df = pd.DataFrame(data={'Col1':np.random.randint(low=20,high=35,size=24) },
                    index=pd.date_range(start='27/10/2019 00:00:00', periods=24,freq='h'))

df.head()

                     Col1
2019-10-27 00:00:00    30
2019-10-27 01:00:00    28
2019-10-27 02:00:00    29
2019-10-27 03:00:00    23
2019-10-27 04:00:00    28

Accessing date parts:

In [4]:
df['Hour'] = df.index.hour
df['Minute'] = df.index.minute
df['Seconds'] = df.index.second
df['Day'] = df.index.day
df['WeekDay_number'] = df.index.weekday
df['WeekDay_text'] = df.index.day_name()
df['Month_number'] = df.index.month
df['Month_short'] = df.index.month_name()
df['Year'] = df.index.year
df['Year-Month'] = df.index.to_period('M')

df.head()

,Col1,Hour,Minute,Seconds,Day,WeekDay_number,WeekDay_text,Month_number,Month_short,Year,Year-Month
2019-10-27 00:00:00,30,0,0,0,27,6,Sunday,10,October,2019,2019-10
2019-10-27 01:00:00,28,1,0,0,27,6,Sunday,10,October,2019,2019-10
2019-10-27 02:00:00,29,2,0,0,27,6,Sunday,10,October,2019,2019-10
2019-10-27 03:00:00,23,3,0,0,27,6,Sunday,10,October,2019,2019-10
2019-10-27 04:00:00,28,4,0,0,27,6,Sunday,10,October,2019,2019-10

Accessing date parts from non-indexed columns:

In [5]:
df_date = pd.DataFrame(data={'Date':pd.date_range(start='27/10/2019 00:00:00', periods=24,freq='h'),
                             'Col1':np.random.randint(low=20,high=35,size=24)})
df_date.head()

                 Date  Col1
0 2019-10-27 00:00:00    28
1 2019-10-27 01:00:00    30
2 2019-10-27 02:00:00    21
3 2019-10-27 03:00:00    30
4 2019-10-27 04:00:00    26

Accessing these date parts by adding .dt after the column:

In [6]:
df_date['Hour'] = df_date['Date'].dt.hour
df_date['Minute'] = df_date['Date'].dt.minute
df_date['Year'] = df_date['Date'].dt.year

df_date.head()

                 Date  Col1  Hour  Minute  Year
0 2019-10-27 00:00:00    28     0       0  2019
1 2019-10-27 01:00:00    30     1       0  2019
2 2019-10-27 02:00:00    21     2       0  2019
3 2019-10-27 03:00:00    30     3       0  2019
4 2019-10-27 04:00:00    26     4       0  2019

Converting to datetime:

In [7]:
df = pd.DataFrame({
    "Date": ["2025-01-01", "2025-01-02", "2025-01-03"],
    "Sales": [100, 150, 200]
})

df["Date"] = pd.to_datetime(df["Date"])
df

        Date  Sales
0 2025-01-01    100
1 2025-01-02    150
2 2025-01-03    200

Setting datetime as index:

In [8]:
df.set_index("Date", inplace=True)
df

            Sales
Date
2025-01-01    100
2025-01-02    150
2025-01-03    200

Accessing Time Series Data - by sepcific date:

In [9]:
df.loc["2025-01-02"]

Sales    150
Name: 2025-01-02 00:00:00, dtype: int64

By date range:

In [10]:
df.loc["2025-01-01":"2025-01-02"]

            Sales
Date
2025-01-01    100
2025-01-02    150

By year, month, or day (via string slicing):

In [11]:
# all data in January 2025
df.loc["2025-01"]

            Sales
Date
2025-01-01    100
2025-01-02    150
2025-01-03    200

In [12]:
# all data in 2025
df.loc["2025"]

            Sales
Date
2025-01-01    100
2025-01-02    150
2025-01-03    200

Create some test data for resampling:

In [13]:
df = pd.DataFrame(data={'Col1':np.random.randint(low=20,high=35,size=1097) },
                    index=pd.date_range(start='27/10/2019 00:00:00', end='27/10/2022 23:00:00', freq='D'))

df.head(20)

            Col1
2019-10-27    31
2019-10-28    20
2019-10-29    25
2019-10-30    24
2019-10-31    34
2019-11-01    21
2019-11-02    25
2019-11-03    34
2019-11-04    24
2019-11-05    32
2019-11-06    27
2019-11-07    26
2019-11-08    20
2019-11-09    20
2019-11-10    29
2019-11-11    22
2019-11-12    24
2019-11-13    25
2019-11-14    28
2019-11-15    28

Frequency and Resampling

In [14]:
# Resample daily to monthly sum
df.resample("ME").sum().head(10)

            Col1
2019-10-31   134
2019-11-30   784
2019-12-31   793
2020-01-31   811
2020-02-29   755
2020-03-31   875
2020-04-30   817
2020-05-31   879
2020-06-30   846
2020-07-31   832

In [15]:
# Resample monthly to daily mean
df.resample("D").mean().head(10)

            Col1
2019-10-27  31.0
2019-10-28  20.0
2019-10-29  25.0
2019-10-30  24.0
2019-10-31  34.0
2019-11-01  21.0
2019-11-02  25.0
2019-11-03  34.0
2019-11-04  24.0
2019-11-05  32.0

Create test data for Shift and Lag demo

In [16]:
np.random.seed(101)
df = pd.DataFrame(data={'Revenue':np.random.randint(low=200,high=350,size=15) }, 
                    index=pd.date_range(start='10/10/2020', periods=15,freq='D'))
df

            Revenue
2020-10-10      295
2020-10-11      211
2020-10-12      281
2020-10-13      270
2020-10-14      263
2020-10-15      287
2020-10-16      275
2020-10-17      337
2020-10-18      240
2020-10-19      332
2020-10-20      263
2020-10-21      260
2020-10-22      310
2020-10-23      205
2020-10-24      340

Add columns for plus and minus 1 period shift

In [17]:
df_example = df.copy()
df_example['RevenueShift+1'] = df_example['Revenue'].shift(periods=1) 
df_example['Revenueshift-1'] = df_example['Revenue'].shift(periods=-1) 
df_example

            Revenue  RevenueShift+1  Revenueshift-1
2020-10-10      295             NaN           211.0
2020-10-11      211           295.0           281.0
2020-10-12      281           211.0           270.0
2020-10-13      270           281.0           263.0
2020-10-14      263           270.0           287.0
2020-10-15      287           263.0           275.0
2020-10-16      275           287.0           337.0
2020-10-17      337           275.0           240.0
2020-10-18      240           337.0           332.0
2020-10-19      332           240.0           263.0
2020-10-20      263           332.0           260.0
2020-10-21      260           263.0           310.0
2020-10-22      310           260.0           205.0
2020-10-23      205           310.0           340.0
2020-10-24      340           205.0             NaN

Difference:

In [18]:
df_example = df.copy()
df_example['RevenueDiff1'] = df_example['Revenue'].diff(periods=1) 
df_example

            Revenue  RevenueDiff1
2020-10-10      295           NaN
2020-10-11      211         -84.0
2020-10-12      281          70.0
2020-10-13      270         -11.0
2020-10-14      263          -7.0
2020-10-15      287          24.0
2020-10-16      275         -12.0
2020-10-17      337          62.0
2020-10-18      240         -97.0
2020-10-19      332          92.0
2020-10-20      263         -69.0
2020-10-21      260          -3.0
2020-10-22      310          50.0
2020-10-23      205        -105.0
2020-10-24      340         135.0

Percentage Change:

In [19]:
df_example = df.copy()
df_example['PctChange1'] = df_example['Revenue'].pct_change(periods=1) 
df_example

            Revenue  PctChange1
2020-10-10      295         NaN
2020-10-11      211   -0.284746
2020-10-12      281    0.331754
2020-10-13      270   -0.039146
2020-10-14      263   -0.025926
2020-10-15      287    0.091255
2020-10-16      275   -0.041812
2020-10-17      337    0.225455
2020-10-18      240   -0.287834
2020-10-19      332    0.383333
2020-10-20      263   -0.207831
2020-10-21      260   -0.011407
2020-10-22      310    0.192308
2020-10-23      205   -0.338710
2020-10-24      340    0.658537

Rolling average:

In [20]:
# 3-day rolling mean
df["Revenue_RollingMean"] = df["Revenue"].rolling(window=3).mean()
df

            Revenue  Revenue_RollingMean
2020-10-10      295                  NaN
2020-10-11      211                  NaN
2020-10-12      281           262.333333
2020-10-13      270           254.000000
2020-10-14      263           271.333333
2020-10-15      287           273.333333
2020-10-16      275           275.000000
2020-10-17      337           299.666667
2020-10-18      240           284.000000
2020-10-19      332           303.000000
2020-10-20      263           278.333333
2020-10-21      260           285.000000
2020-10-22      310           277.666667
2020-10-23      205           258.333333
2020-10-24      340           285.000000